// Copyright © 2024 Ingka Holding B.V. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/opencensus_metrics.tpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"
	"log"
	"time"

	"go.opencensus.io/plugin/ochttp"
	"go.opencensus.io/stats"
	"go.opencensus.io/stats/view"
	"go.opencensus.io/tag"
)

var (
	serverHistogramResultTag       = tag.MustNewKey("result")
	serverHistogramMethodNameTag   = tag.MustNewKey("method_name")
	serverHistogramInstanceNameTag = tag.MustNewKey("instance_name")

	serverHistogram = stats.Float64("server_server_duration_ms", "Time spent in ms on running an operation of type <Server> in package <server>", stats.UnitMilliseconds)
)

// ServerWithMetrics implements Server interface with all methods wrapped
// with metrics
type ServerWithMetrics struct { //nolint:golint
	base         Server
	instanceName string
}

// NewWithMetrics returns an instance of the Server decorated with metrics
func NewWithMetrics(base Server, instanceName string) Server {
	if err := view.Register(
		&view.View{
			Name:        serverHistogram.Name(),
			Description: serverHistogram.Description(),
			Measure:     serverHistogram,
			TagKeys: []tag.Key{
				serverHistogramResultTag,
				serverHistogramMethodNameTag,
				serverHistogramInstanceNameTag,
			},
			Aggregation: ochttp.DefaultLatencyDistribution,
		},
	); err != nil {
		log.Fatalf("could not register view (%v): %v", serverHistogram.Name(), err)
	}

	return ServerWithMetrics{
		base:         base,
		instanceName: instanceName,
	}
}

// ListenAndServe implements Server
func (_d ServerWithMetrics) ListenAndServe() (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		_ctx, err := tag.New(context.Background(),
			tag.Insert(serverHistogramInstanceNameTag, _d.instanceName),
			tag.Insert(serverHistogramMethodNameTag, "ListenAndServe"),
			tag.Insert(serverHistogramResultTag, result),
		)
		if err != nil {
			log.Printf("could not create tag with context for instance (%v) method (%v): %v",
				_d.instanceName,
				"ListenAndServe",
				err,
			)
			return
		}
		stats.Record(
			_ctx,
			serverHistogram.M(float64(time.Since(_since)/time.Millisecond)),
		)
	}()

	return _d.base.ListenAndServe()
}

// Shutdown implements Server
func (_d ServerWithMetrics) Shutdown(ctx context.Context) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		_ctx, err := tag.New(context.Background(),
			tag.Insert(serverHistogramInstanceNameTag, _d.instanceName),
			tag.Insert(serverHistogramMethodNameTag, "Shutdown"),
			tag.Insert(serverHistogramResultTag, result),
		)
		if err != nil {
			log.Printf("could not create tag with context for instance (%v) method (%v): %v",
				_d.instanceName,
				"Shutdown",
				err,
			)
			return
		}
		stats.Record(
			_ctx,
			serverHistogram.M(float64(time.Since(_since)/time.Millisecond)),
		)
	}()

	return _d.base.Shutdown(ctx)
}
