name: 🔬 PR Analysis

on:
  pull_request:

jobs:
  pr-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Triage PR title
        if: ${{ startsWith(github.head_ref, 'dependabot/') != true }}
        uses: amannn/action-semantic-pull-request@v5.5.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check out source code
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Setup deps
        shell: bash
        run: |
          # A linter that helps with getting the import ordering right
          go install github.com/hedhyw/go-import-lint/cmd/go-import-lint@latest

          # A state-of-the-art golang linter.
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run .pre-commit-config.yaml
        uses: pre-commit/action@v3.0.0

      - name: Build Docker
        shell: bash
        run: |
          docker build . -t ${{ github.repository }}:${{ github.sha }}
