name: 🔬 PR Analysis

on:
  pull_request:

permissions:
  pull-requests: read
  contents: read
  id-token: write

jobs:
  pr-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Triage PR title
        if: ${{ startsWith(github.head_ref, 'dependabot/') != true }}
        uses: amannn/action-semantic-pull-request@v5.5.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check out source code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Setup deps
        shell: bash
        run: |
          # A linter that helps with getting the import ordering right
          go install github.com/hedhyw/go-import-lint/cmd/go-import-lint@latest

          # A state-of-the-art golang linter.
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run .pre-commit-config.yaml
        uses: pre-commit/action@v3.0.0

      - name: Build Docker
        shell: bash
        run: |
          docker build . -t ${{ github.repository }}:${{ github.sha }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        id: bump_version
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
          RELEASE_BRANCHES: main
          # custom tagging policy adapted to conventional commits
          MAJOR_STRING_TOKEN: feat!
          MINOR_STRING_TOKEN: feat
          DEFAULT_BUMP: patch
          DRY_RUN: true # Do not push the tag during PR

      - name: JFrog scanning
        uses: ingka-group/iam-proxy/.github/composites/jfrog@main
        with:
          jf_url: ${{ secrets.JF_URL }}
          jf_oidc_provider: ${{ secrets.JF_OIDC_PROVIDER }}
          jf_oidc_audience: ${{ secrets.JF_OIDC_AUDIENCE }}
          jf_repo: ${{ secrets.JF_GO_DEV_REPO }}
          version: ${{ steps.bump_version.outputs.new_tag }}
